import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowUpRight, ArrowRight, ArrowDown, BedDouble, CalendarDays, Menu, X, MessageCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SITE, type Project, type PlanStep, type Status } from "@/data/projects";

export const sharingMeta = (canonicalUrl: string) => [
 { property: "og:image", content: `${SITE.url}/og-image.png` },
 { name: "twitter:image", content: `${SITE.url}/og-image.png` },
 { property: "og:image:width", content: "1200" },
 { property: "og:image:height", content: "630" },
 { property: "og:url", content: canonicalUrl },
];
export const GENERIC_MESSAGE = "Hi, I'm interested in Emaar's projects at Dubai Creek Harbour.";
export const projectMessage = (name: string) => `Hi, I'm interested in ${name} at Dubai Creek Harbour. Please send me the latest price list, payment plan and available units.`;
export const whatsappUrl = (message = GENERIC_MESSAGE) => `https://wa.me/${SITE.whatsapp}?text=${encodeURIComponent(message)}`;
export const DISCLAIMER = "DXB Creek Harbour is an independent property showcase. The projects shown are developed by Emaar Properties PJSC; this website is not owned, operated or endorsed by Emaar. Prices are the developer's own figures as checked on 7 October 2026, and payment plans and handover dates are the developer's stated terms and dates. All can change without notice and availability is limited — confirm current details before you commit. Images and brochures are Emaar's; project names and brochures belong to their owners.";
export function WhatsApp({ message = GENERIC_MESSAGE, children = "WhatsApp us", variant = "default", className = "" }: { message?: string; children?: React.ReactNode; variant?: "default" | "outline" | "brass" | "heroOutline"; className?: string }) {
 return <Button asChild variant={variant} className={className}><a href={whatsappUrl(message)} target="_blank" rel="noopener noreferrer"><MessageCircle />{children}</a></Button>;
}
export function Wordmark() { return <Link to="/" className="dxbch-lockup" aria-label="DXB Creek Harbour, home"><svg className="dxbch-mark" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 40" aria-hidden="true" focusable="false"><path className="dxbch-arch" d="M1 30V3A34.167 34.167 0 0 1 29 3V30H26V14.5A11 11 0 0 0 4 14.5V30ZM6 30V14.5A9 9 0 0 1 24 14.5V30H21V14.5A6 6 0 0 0 9 14.5V30Z"/><path className="dxbch-water" d="M0 33.5C10.5 31.5 19.5 31.5 30 33.5C19.5 35.5 10.5 35.5 0 33.5ZM15 38.75C19.9 37.083 24.1 37.083 29 38.75C24.1 40.417 19.9 40.417 15 38.75Z"/></svg><span className="dxbch-words"><span className="dxbch-dxb">DXB</span><span className="dxbch-sub">Creek Harbour</span></span></Link>; }
export function Header() {
 const [open,setOpen] = useState(false);
 return <header className="site-header"><div className="container header-inner"><Wordmark/><nav className="main-nav" aria-label="Main navigation"><Link to="/" hash="projects" className="nav-link">The projects</Link><Link to="/" hash="payment-plans" className="nav-link">Payment plans</Link><Link to="/" hash="district" className="nav-link">The neighbourhood</Link><WhatsApp variant="outline" className="header-wa">Let's talk <ArrowUpRight/></WhatsApp></nav><Button variant="ghost" size="icon" className="mobile-toggle" aria-label={open ? "Close navigation" : "Open navigation"} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div>{open&&<nav className="mobile-nav" aria-label="Mobile navigation"><Link to="/" hash="projects" onClick={()=>setOpen(false)}>The projects</Link><Link to="/" hash="payment-plans" onClick={()=>setOpen(false)}>Payment plans</Link><Link to="/" hash="district" onClick={()=>setOpen(false)}>The neighbourhood</Link><WhatsApp/></nav>}</header>;
}
export function Footer() {return <><footer className="site-footer"><div className="container"><div className="footer-top"><Wordmark/><nav className="footer-nav" aria-label="Footer navigation"><Link to="/" hash="projects">Projects</Link><Link to="/" hash="district">The district</Link><Link to="/" hash="faq">FAQs</Link><a href={whatsappUrl()} target="_blank" rel="noopener noreferrer">WhatsApp <ArrowUpRight className="inline size-3"/></a></nav></div><p className="disclaimer">{DISCLAIMER}</p>{SITE.dldPermit&&<p className="disclaimer">DLD Permit No. {SITE.dldPermit}</p>}<div className="footer-bottom"><span>DXB Creek Harbour · Independent property showcase</span><span>Dubai, United Arab Emirates</span></div></div></footer><Button asChild className="floating-wa" size="icon"><a href={whatsappUrl()} target="_blank" rel="noopener noreferrer" aria-label="Chat on WhatsApp" title="Chat on WhatsApp"><MessageCircle/></a></Button></>;}
export function StatusBadge({status}:{status:Status}) {return <span className="status-badge">{status}</span>;}
export function ProjectArt({project,index=0,large=false}:{project:Project;index?:number;large?:boolean}) {return <div className={`project-art ${index%3===1?'tone-sand':index%3===2?'tone-ink':''} ${large?'detail-banner':''}`}><span className="art-caption">Dubai Creek Harbour</span>{!large&&<StatusBadge status={project.status}/>}{large?<p className="art-name">{project.name}</p>:<h3>{project.name}</h3>}{project.brand&&<span className="brand">{project.brand}</span>}</div>;}
export function ProjectCard({project,index=0}:{project:Project;index?:number}) {
 const [failedSrc,setFailedSrc]=useState<string|null>(null);
 const image=project.images[0];
 const hasImage=image && failedSrc!==image.src;
 return <article className="project-card">{hasImage?<div className="card-cover"><img src={image.src} alt={image.caption} loading="lazy" decoding="async" width={1200} height={750} ref={element=>{if(element?.complete && element.naturalWidth===0)setFailedSrc(image.src);}} onError={()=>setFailedSrc(image.src)}/><StatusBadge status={project.status}/></div>:<ProjectArt project={project} index={index}/>}<div className="card-body">{hasImage&&<><h3 className="card-name">{project.name}</h3>{project.brand&&<p className="card-brand">{project.brand}</p>}</>}<p className="card-price">{project.priceDisplay??"Price on request"}</p><p className="price-note">{project.priceNote??"Ask on WhatsApp for current availability"}</p><div className="card-facts"><span><BedDouble/>{project.bedrooms}</span><span><CalendarDays/>{project.handover}</span></div><div className="card-actions"><Button asChild variant="outline" size="sm"><Link to="/projects/$slug" params={{slug:project.slug}}>View project <ArrowUpRight/></Link></Button><WhatsApp message={projectMessage(project.name)} className="card-whatsapp text-xs">WhatsApp</WhatsApp></div></div></article>;}
export function PlanBar({steps}:{steps:PlanStep[]}) {return <div className="plan-bar" aria-label={steps.map(s=>`${s.label}: ${s.percent}%`).join(', ')}>{steps.map(step=><div key={step.label} className={`plan-segment ${step.label.startsWith('On booking')?'booking':step.label.startsWith('On handover')?'handover':'construction'}`} style={{flexGrow:step.percent,flexBasis:0}} title={`${step.label}: ${step.percent}%`}>{step.percent}%</div>)}</div>;}
export function CtaBand({project}:{project?:Project}) {return <section className="cta-band"><div className="container cta-inner"><div><span className="eyebrow">A conversation, not a commitment</span><h2>{project?`Interested in ${project.name}? Let's talk.`:"Tell us your budget and bedrooms — we'll send what's available today."}</h2></div><WhatsApp variant="brass" message={project?projectMessage(project.name):GENERIC_MESSAGE}>WhatsApp us <ArrowUpRight/></WhatsApp></div></section>;}
export function ProjectNotFound() {return <main className="container unavailable"><span className="eyebrow">Project unavailable</span><h1>Let's find your place<br/>at the Creek.</h1><p>We couldn't find that project. Explore the current collection or ask us on WhatsApp.</p><div className="flex flex-wrap gap-3"><Button asChild><Link to="/" hash="projects">View all projects <ArrowRight/></Link></Button><WhatsApp variant="outline"/></div></main>;}
export { ArrowDown, ArrowUpRight };
